### ISSUE TITLE
Community Announcement

### ISSUE THREAD

**Issue by aidapsibr** [psibr/REstate#4]
We are nearing a ready to live: v1.

Here is what remains:
- [ ] File repository
- [ ] XML comments
- [ ] BDD/Unit/Integration Tests
- [ ] Getting started documentation.

**Comment by aidapsibr** [comment]
@sle118 I think you were interested in this project quite a bit back, wanted to let you know the project has made some major progress now.

**Comment by sle118** [comment]
@psibernetic  Thank you for the notification.  

Was this related to wrapping up a stateless state machine (https://github.com/dotnet-state-machine/stateless) as a sever?  I have a complex state machine built which I would love to see being exposed as an http server.

Let me know!

**Comment by aidapsibr** [comment]
@sle118 It is similar, but may or may not satisfy your needs.

There were lots of problems with directly using Stateless as the engine and doing proxy calls or being HTTP friendly. As such the engine here is a subset of the the features in Stateless. Additionally there are more well-defined rules around connectors to support remoting scenarios. Check out the Examples for Client Server and Job system to get an idea of how it can be used. 

I do not have a HTTP/1.1 host in this project as the .NET -> .NET scenario was better covered with gRPC and binary serialization practices, but building a specialized host for your machines should be simple enough. We can set up a time to talk and screen share if you want an intro or deep-dive to see if the tool could work for you.

**Comment by sle118** [comment]
@psibernetic In other words, a new state machine was created for this project? I am guessing I would need to port the stateless state machine code to this new platform, or would it be possible to wrap the existing code in a simple way?

I don't have much bandwidth right now to work on the personal project for which I have a state machine. I'm building a mini-cnc and playing with some home grown PCBs when I am not flying one of my DIY drones, after long working hours... Which means the little spare time is spread thin!

I might resume work on this later this fall.
